config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

resources :tags
resources :works
resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
has_many :works
end

app/models/work.rb
class Work < ApplicationRecord
belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordInvalid, with: :validation_failed

  private
    def validation_failed
      redirect_to root_url, notice: "Inquiry box can't be left blank. Please ensure you type in a message or return to home page."
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end
  def new
    @comment = Comment.new
  end

  def show
    @comment = Comment.find(params[:id])
    # redirect_to new_comment_path
  end

  def create
    @comment = Comment.create!(comment_params)
    if @comment.save
    flash[:notice] = "Thank you for your message and cant wait to read it!"
    redirect_to comments_path
  end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to comments_path
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def show
    @work = Work.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment do |f| %>

<%= f.label :Inquiry %>
<%= f.text_field :body %>

<%= f.submit "Submit"%>

<% end %>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/comments/index.html.erb
<header>CONTACTS US</header>

<h3>Leave us a comment if you have any questions, <br>
  have an inquiry regarding a service or want to leave us a review!<br>
  We would love to hear from you even if its just to say HI!<br></h3>

<h4>If you have an inquiry, please include the following in your inquiry.</h4>

<ol>
<li>Your name</li>
<li>Your contact information</li>
<li>Also be as specific as possible with your inquiry</li>
</ol>

<h4>&hearts; Can't wait to hear from you beautiful! &hearts;</h4>

<h4><a href="/comments/new">Contact form</a></h4>


<% @comments.each do |comment| %>
<div class="comment">

<p><%= comment.body %></p>
<div class="btn">
<%= link_to "Edit", edit_comment_path(comment), class: "button" %>
<%= form_for comment, method: :delete do |f|  %>
<% f.submit "Delete"%>
<% end %>
</div>
</div>
<% end %>

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NetsuheBekele</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|EB+Garamond|Libre+Barcode+39+Text|Lobster+Two|Poiret+One|Quicksand" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <div class="menu">
      <ul>
        <a href="/"><li>HOME</li></a>
        <a href="/works"><li>PORTFOLIO</li></a>
        <a href="/tags"><li>SERVICES &amp; PRICES</li></a>
        <a href="/comments"><li>CONTACTS US</li></a>
        <a href="#" class="fa fa-instagram"></a>
      </ul>
    </div>
  </nav>
  <% flash.each do |type, message| %>
    <p class="flash <%= type %>"><%= message %></p>
  <% end %>
    <%= yield %>
  </body>

  <footer>est. 2017 &hearts;</footer>
</html>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<header>SERVICES</header>
<!-- The services will be represented by the tag class  -->

<h2>Bridal Makeup</h2>
<ol>
<li>Bride only(lashes included) $175</li>
<li>Bride only for half day starting at $400</li>
<li>Bride only for full day please contact us for pricing</li>
<li>Bridesmaids up to 4, each $75</li>
<li>Bridesmaids of more than 4, please contact us for pricing</li>
</ol>

<h2>Special Events</h2>
<ol>
<li>Birthdays(lashes included)  $75</li>
<li>Blacktie Events(lashes included) $75</li>
<li>Special Functions(lashes included) $75</li>
<li>For any other specific needs please contact us for pricing.</li>
</ol>

<h2>Special FX</h2>

<ol>
<li>All starting at $100</li>
</ol>

<p>Please contact us for further details and pricing.</p>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<h1>Tags#show</h1>
<p>Find me in app/views/tags/show.html.erb</p>

app/views/welcome/index.html.erb
<header>Netsuhe Bekele</header>

<h6>"Be your own kind of Beauty!"</h6>

<!-- <header>
  <nav>
  <div class="menu">
    <ul>
      <a href="/works"><li>PORTFOLIO</li></a>
      <a href="/tags"><li>PRICES</li></a>
      <a href="/comments"><li>CONTACTS US</li></a>
    </ul>
  </div>
</nav>
</header> -->

app/views/works/edit.html.erb
<h1>Works#edit</h1>
<p>Find me in app/views/works/edit.html.erb</p>

app/views/works/index.html.erb
<header>PORTFOLIO</header>
<!-- This is the works class and I have it render as porfolio -->
<h2>Bridal</h2>
<div class="image">
<% @works.each do |work| %>
<% if work.tag_id == 1 %>
<%= image_tag work.img_url %>
<% end %>
<% end %>

<h2>Special Events</h2>

<% @works.each do |work| %>
<% if work.tag_id == 2 %>
<%= image_tag work.img_url %>
<% end %>
<% end %>

<h2>Special FX</h2>

<% @works.each do |work| %>
<% if work.tag_id == 3 %>
<%= image_tag work.img_url %>
<% end %>
<% end %>
</div>

app/views/works/new.html.erb
<h1>Works#new</h1>
<p>Find me in app/views/works/new.html.erb</p>

app/views/works/show.html.erb
<h1>Works#show</h1>
<p>Find me in app/views/works/show.html.erb</p>